### PR TITLE
Add test for nested if statements that is breaking

### PR DESCRIPTION
**Pull request by timneutkens**
I’m investigating adding async-to-promises to Next.js by default. While adding it to zeit.co I ran into this specific error so I’ve created a failing test for it.

Note that I've slimmed down the existing code that broke, it's still producing the same error but the code itself is not super valid at runtime, it is at compile time though 🙏

### CODE REVIEW

**Comment by rpetrich** [comment]
Thx @timneutkens. I've fixed this in master and slimmed your test case further.

**Comment by timneutkens** [comment]
Awesome @rpetrich 💯

**Comment by timneutkens** [comment]
@rpetrich just tried it against zeit.co again (with the code built from master) seems like something goes wrong still, I've added the input/output to a Gist:

https://gist.github.com/timneutkens/fd4d181e07b4813f78ea1f75d7859b71

```
[Attempt: 4] _temp3 is not defined: []
ReferenceError: [Attempt: 4] _temp3 is not defined: []
    at .next/server/static/development/pages/home.js:14048:22
    at .next/server/static/development/pages/home.js:14049:14
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by rpetrich** [comment]
@timneutkens That uncovered a separate bug with the `inlineHelpers` option. I've corrected and pulled your full gist in as a test case.

**Comment by timneutkens** [comment]
💯 Awesome!

**Pull request merged**
